export type PurchaseKind = 'mandatory' | 'optional';
export type PurchaseGroup = 'food' | 'fun' | 'shirt' | 'hat' | 'trinket';

export type PurchaseItem = {
  id: string;
  name: string;
  kind: PurchaseKind;
  group: PurchaseGroup;
  price: number;
  description: string;
  effect: string;
  hungerGain: number;
  satiation: number;
  image: number | null;
  wearable?: 'shirt' | 'hat' | 'trinket';
};

export const PURCHASES: PurchaseItem[] = [
  {
    id: 'food-bowl',
    name: 'Миска еды',
    kind: 'mandatory',
    group: 'food',
    price: 35,
    description: 'Обычная еда на сегодня.',
    effect: 'Кот становится сытее.',
    hungerGain: 30,
    satiation: 2,
    image: require('../../assets/images/miska.png'),
  },
  {
    id: 'food-premium',
    name: 'Сытный обед',
    kind: 'mandatory',
    group: 'food',
    price: 55,
    description: 'Порция побольше на сегодня.',
    effect: 'Кот дольше не голоден.',
    hungerGain: 40,
    satiation: 4,
    image: require('../../assets/images/food2.png'),
  },
  {
    id: 'food-deluxe',
    name: 'Праздничный ужин',
    kind: 'mandatory',
    group: 'food',
    price: 80,
    description: 'Самая большая порция.',
    effect: 'Кот получает максимум сытости.',
    hungerGain: 50,
    satiation: 5,
    image: require('../../assets/images/food3.png'),
  },
  {
    id: 'care-brush',
    name: 'Расчёска',
    kind: 'optional',
    group: 'fun',
    price: 15,
    description: 'Купи чтобы кота можно было гладить',
    effect: 'После покупки нажми на кота дома.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/raschestka.png'),
  },
  {
    id: 'toy-ball',
    name: 'Мячик',
    kind: 'optional',
    group: 'fun',
    price: 18,
    description: 'Игрушка для весёлой игры.',
    effect: 'Можно поиграть, когда есть свободные монеты.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/ball.png'),
  },
  {
    id: 'shirt-stripe',
    name: 'Полосатая кофта',
    kind: 'optional',
    group: 'shirt',
    price: 16,
    description: 'Простая кофта на каждый день.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/polosataya-kofta.png'),
    wearable: 'shirt',
  },
  {
    id: 'shirt-star',
    name: 'Кофта со звездой',
    kind: 'optional',
    group: 'shirt',
    price: 24,
    description: 'Кофта с яркой звёздочкой.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/star-kofta.png'),
    wearable: 'shirt',
  },
  {
    id: 'shirt-warm',
    name: 'Тёплая кофта',
    kind: 'optional',
    group: 'shirt',
    price: 36,
    description: 'Самая уютная кофта.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/warm-kofta.png'),
    wearable: 'shirt',
  },
  {
    id: 'hat-cap',
    name: 'Кепка',
    kind: 'optional',
    group: 'hat',
    price: 12,
    description: 'Лёгкая кепка для прогулки.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/kepka.png'),
    wearable: 'hat',
  },
  {
    id: 'hat-bow',
    name: 'Бантик',
    kind: 'optional',
    group: 'hat',
    price: 20,
    description: 'Нарядный бантик.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/bantik.png'),
    wearable: 'hat',
  },
  {
    id: 'hat-crown',
    name: 'Корона',
    kind: 'optional',
    group: 'hat',
    price: 40,
    description: 'Самая заметная шляпка.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/crown.png'),
    wearable: 'hat',
  },
  {
    id: 'trinket-bell',
    name: 'Колокольчик',
    kind: 'optional',
    group: 'trinket',
    price: 10,
    description: 'Маленький звонкий колокольчик.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/kolokolchik-shop.png'),
    wearable: 'trinket',
  },
  {
    id: 'trinket-scarf',
    name: 'Шарфик',
    kind: 'optional',
    group: 'trinket',
    price: 18,
    description: 'Мягкий шарфик на шею.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/sharf.png'),
    wearable: 'trinket',
  },
  {
    id: 'trinket-medal',
    name: 'Медаль',
    kind: 'optional',
    group: 'trinket',
    price: 30,
    description: 'Блестящая медаль для особого дня.',
    effect: 'Можно надеть в гардеробе.',
    hungerGain: 0,
    satiation: 0,
    image: require('../../assets/images/medal.png'),
    wearable: 'trinket',
  },
];

export const SHOP_GROUPS: { id: PurchaseGroup; title: string }[] = [
  { id: 'food', title: 'Корм' },
  { id: 'fun', title: 'Развлечения' },
  { id: 'shirt', title: 'Кофточки' },
  { id: 'hat', title: 'Шляпки' },
  { id: 'trinket', title: 'Аксессуары' },
];

export function findPurchase(id: string): PurchaseItem | null {
  return PURCHASES.find((item) => item.id === id) ?? null;
}
